source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CSTip_Example', :exclusive => true do
  pod 'CSTip', :path => '../'
end

target 'CSTip_Tests', :exclusive => true do
  pod 'CSTip', :path => '../'

  
end
